// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "hero": { "headline": string; "subheading": string; "tagline": string }; "details": { "sectionLabel": string; "cards": Array<{ "id": string; "emoji": string; "title": string; "body": string; "sub": string }> }; "rsvp": { "sectionLabel": string; "headline": string; "body": string; "cta": string } }; "itinerary": { "badge": string; "title": string; "subtitle": string }; "signup": { "badge": string; "title": string; "subtitle": string } };
  export const data: { "pdfs": Array<{ "id": string; "title": string; "fileUrl": string; "display": string; "caption": string }> };
  export const home: { "hero": { "headline": string; "subheading": string; "tagline": string }; "details": { "sectionLabel": string; "cards": Array<{ "id": string; "emoji": string; "title": string; "body": string; "sub": string }> }; "rsvp": { "sectionLabel": string; "headline": string; "body": string; "cta": string } };
  export const itinerary: { "badge": string; "title": string; "subtitle": string };
  export const pdfs: Array<{ "id": string; "title": string; "fileUrl": string; "display": string; "caption": string }>;
  export const signup: { "badge": string; "title": string; "subtitle": string };
}
